added ViewBinding, compiled items in activity_main.xml, all values mo…
hassantillkassan/RecipesApp pull request #1
Opened 2024-08-20 18:34 UTC by hassantillkassan

…ved to resources

2024-08-20 18:40 UTC, hassantillkassan commented
Иконку `ic_heart.svg` скруглил через [yqnn.github.io ](https://yqnn.github.io/svg-path-editor/) чтоб студия не ругалась

2024-08-21 12:26 UTC, ievetrovdev commented
> Иконку `ic_heart.svg` скруглил через [yqnn.github.io ](https://yqnn.github.io/svg-path-editor/) чтоб студия не ругалась

а зачем? не ругалась на что?)

2024-08-21 12:36 UTC, ievetrovdev commented
Нейминги коммита, пулл реквеста и ветки следует делать все в едином стиле (который принят в сообществе). Как правило это аббревиатура название проекта.

Например:
RA-03 create navigation buttons (для названия PR и сообщения коммита)
RA-03-create-navigation-buttons (для названия ветки, разделение всех слов дефисами)

2024-08-21 12:45 UTC, ievetrovdev requested changes

2024-08-21 12:45 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
>          enableEdgeToEdge()
Давай уберем enableEdgeToEdge(), чтобы контент активити (и фрагмента) не заезжал на статусбар и навбар.

2024-08-21 12:45 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginBottom="55dp"
Обрати внимание на отступ между контейнером с кнопками до нижнего навбара. По макету это 8dp.

2024-08-21 12:45 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginBottom="55dp"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-08-21 12:45 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="navigationBarColor">#F4FAFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-08-21 12:45 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingStart="18dp"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-08-21 12:45 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingStart="18dp"
Паддинги внутри предлагаю убрать, будем все делать адаптивно

2024-08-21 18:02 UTC, hassantillkassan commented
> > Иконку `ic_heart.svg` скруглил через [yqnn.github.io ](https://yqnn.github.io/svg-path-editor/) чтоб студия не ругалась
> 
> а зачем? не ругалась на что?)
Вот. Это пример из другого проекта. Загрузил ту же иконку
![image](https://github.com/user-attachments/assets/28b11a3b-21b9-4ca5-93c0-92ba0768bb02)

2024-08-21 19:50 UTC, hassantillkassan commented
Теперь без паддингов, к сожалению, текст на кнопке переносится из-за иконки. Device: Pixel 7a

2024-08-22 16:32 UTC, ievetrovdev commented
!!! Проигнорировано

<img width="927" alt="Снимок экрана 2024-08-22 в 19 32 02" src="https://github.com/user-attachments/assets/ab2399f3-2339-40a8-a339-01dbfb3bab1d">

2024-08-22 16:33 UTC, ievetrovdev commented
> > > Иконку `ic_heart.svg` скруглил через [yqnn.github.io ](https://yqnn.github.io/svg-path-editor/) чтоб студия не ругалась
> > 
> > 
> > а зачем? не ругалась на что?)
> > Вот. Это пример из другого проекта. Загрузил ту же иконку. Ну это не ошибка, а предупреждение о слишком длинном path вектора
> > ![image](https://private-user-images.githubusercontent.com/52125620/360029373-28b11a3b-21b9-4ca5-93c0-92ba0768bb02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDQ2MTYsIm5iZiI6MTcyNDM0NDMxNiwicGF0aCI6Ii81MjEyNTYyMC8zNjAwMjkzNzMtMjhiMTFhM2ItMjFiOS00Y2E1LTkzYzAtOTJiYTA3NjhiYjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE2MzE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNWM4NTg3YzQyYmNmNzMyZjRlNmRiZWY3MzYwNmExZDdlNDY0NzJkMTU1M2QxYTZmZTMzODkxMjA1YWMwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HNroSMtMfA4soaiudeHYwjnQ90qvYKNWd966BcCzsoU)

иконка изменила свое положение после сервиса (сравни после экспорта из фигмы и после рефакторинга)

2024-08-22 16:37 UTC, ievetrovdev commented
> Теперь без паддингов, к сожалению, текст на кнопке переносится из-за иконки. Device: Pixel 7a ![image](https://private-user-images.githubusercontent.com/52125620/360077577-a0765415-d005-484e-9e7a-20a81e0a7856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDQ5NDIsIm5iZiI6MTcyNDM0NDY0MiwicGF0aCI6Ii81MjEyNTYyMC8zNjAwNzc1NzctYTA3NjU0MTUtZDAwNS00ODRlLTllN2EtMjBhODFlMGE3ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE2MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZWIwMmNlZmE0NGRjYTNhMDkyOWFmM2U3MzBiNjlkZDJjOTFlZDhlYjQ3Yzg5NTU0NjJiNGZhMTk2NjJlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2SfTzdxRf2xUHrOO3Ft8eYpE21E7hjDfH6g1tN335qU)

Чтобы убрать переносы добавь атрибут android:maxLines="1"

2024-08-22 16:37 UTC, ievetrovdev requested changes

2024-08-22 16:37 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:paddingHorizontal">35.5dp</item>
Паддинг не убран

2024-08-22 16:37 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8dp</item>
Все размеры выносим в ресурсы

2024-08-22 16:37 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_width">match_parent</item>
Атибуты layout_width и layout_height как правило в стиль не выносятся. Концептуально они не относятся к оформлению.

2024-08-22 16:37 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            app:iconSize="24dp"
В ресурсы

2024-08-22 16:37 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="navigationBarColor">@color/backgroundColor</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

В данном случае ты еще используешь ссылки на цвет из текущего же документа. Это некорректно, оставляем только уникальные айтемы цветов.

2024-08-22 19:42 UTC, closed without merging