RA-08 rv implementation
hassantillkassan/RecipesApp pull request #10
Opened 2024-09-09 17:14 UTC by hassantillkassan

2024-09-09 17:21 UTC, hassantillkassan commented
Не получилось у меня реализовать кастомный ripple-эффект с бликом, проходящим по карточке во время нажатия. Как бы ни пытался, через Animation или ObjectAnimator. Единственное, что получилось, это анимировать саму карточку при нажатии в `setOnClickListener `- сузил и раздул её по размерам, но это не то, что нужно) Из кода убрал

2024-09-10 15:19 UTC, ievetrovdev requested changes

2024-09-10 15:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +        return ViewHolder(view)
Давай сразу во viewHolder передавать binding, так код станет более читаемым
ItemCategoryBinding.inflate(LayoutInflater.from(parent.context), parent, false).
ecyclerView.ViewHolder() в конструктор принимает view, его можно получить через binding.root

2024-09-10 15:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +            _binding = ItemCategoryBinding.bind(view)
Когда ты присваиваешь переменным значения напрямую по типу: private var _binding: ItemCategoryBinding? = null, это равносильно блоку init. То есть можно сразу было написать  private val binding: ItemCategoryBinding = ItemCategoryBinding.bind(view). Но лучше передавать bindnig сразу в конструктор ViewHolder вместо view

2024-09-10 15:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +        fun bind(category: Category) {
Работает, но не оптимизировано. ViewHolder должен отвечать только за хранение вьюх, а логика, связанная с изменением данных, должна быть вынесена на уровень адаптера в onBindViewHolder.
Если заполнить этот список большим объемом данных, RecyclerView создаст примерно 12 viewHolders и будет переиспользовать эти блоки, меняя лишь содержание внутри в функции onBindViewHolder. Сейчас у тебя viewHolder пустой и этой магии не происходит, просто вынесена вся логика из onBindViewHolder в функцию bind.

2024-09-10 15:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +            layoutManager = GridLayoutManager(context, 2)
этот параметр лучше вынести в xml с добавлением app:layoutManager, а цифра 2 уже указана в spanCount

2024-09-11 17:58 UTC, ievetrovdev commented
На этом этапе элементы адаптера в приложении должны соответствовать дизайну из фигмы. Сейчас у тебя большинство параметров прописаны как tools в item_category. Tools параметры видны только на макете студии, надо сделать их app. Рекомендую вынести в стиль тексты. Если глянешь экраны в фигме, на других экранах настройки текста похожи 
<img width="302" alt="Снимок экрана 2024-09-11 в 20 54 38" src="https://github.com/user-attachments/assets/1ff3814a-0f2f-4867-ac8c-95fabbb36166">

2024-09-11 17:59 UTC, ievetrovdev requested changes

2024-09-11 17:59 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +            binding.ivCategoryImage.setImageDrawable(drawable)
Еще немного про описание контента. contentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов.

Для изображений элементов категорий тоже следует добавить описание. Причем подход  рекомендую через адаптер – чтобы у каждого элемента было свое описание.

Можно задавать картинкам категорий что-то вроде "Изображение категории название_категории".

2024-09-13 17:56 UTC, ievetrovdev requested changes

2024-09-13 17:56 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListFragment.kt
> +        val itemDecoration = SpaceItemDecoration(resources.getDimensionPixelSize(R.dimen.item_spacing))
Не совсем понятно, почему решил использовать itemDecoration? Его основная проблема в том, что макет XML и реальное приложение будут показывать разные экраны. Если какие-то проблемы с отображением без него, скорее всего дело в неправильной верстке, лучше поправить её

2024-09-13 17:56 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
>      android:clickable="true"
В твоем случае достаточно прописать в cardView нужный magrinVertical. Глянь по макету во fragment_list_categories, как выглядит твой список и поправь по дизайну из фигмы

2024-09-15 11:07 UTC, ievetrovdev approved these changes
Молодец, сделано всё как надо. Оставил некритичный коммент, но для расширения кругозора,  лучше его поправить в следующем ПР

2024-09-15 11:07 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/CategoriesListAdapter.kt
> +        binding.ivCategoryImage.contentDescription = "Изображение категории ${category.title}"
Чтобы была возможность переводить такие динамические надписи, лучше вынести её в ресурсы, с использованием аргументов. 
Подробнее можно почитать здесь: https://developer.android.com/guide/topics/resources/string-resource?hl=ru#formatting-strings

2024-09-15 16:57 UTC, merged