RA-11 recipe list screen
hassantillkassan/RecipesApp pull request #13
Opened 2024-09-24 18:49 UTC by hassantillkassan

2024-09-25 18:35 UTC, ievetrovdev requested changes

2024-09-25 18:35 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +            replace(R.id.mainContainer, recipeFragment)
Есть более короткая запись через `replace<RecipeFragment>`,  туда же сразу передавать аргументы args = . И от newInstance можно полностью избавиться

2024-09-25 18:35 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/OnNavigationListener.kt
> +    fun openRecipeByRecipeId(recipeId: Int)
Если и использовать отдельную навигацию, то лучше называть в одном стиле

2024-09-25 18:35 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/RecipesListAdapter.kt
> +        val binding = viewHolder.binding
Не особо сильно эта переменная улучшила читаемость кода. Может лучше просто обернуть код ниже в конструкцию with(viewHolder.binding){}

2024-09-25 18:35 UTC, ievetrovdev commented on app/src/main/res/values-ru/strings.xml
> +    <string name="recipe_image_description">Изображение рецепта %s</string>
Давай придерживаться единого столя наименования строк. Чтобы легко их было найти по быстрому поиску и не спутать с другими айдишниками, в начало каждой строки добавим приставку text_

2024-09-26 17:35 UTC, ievetrovdev requested changes

2024-09-26 17:35 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +                args = bundleOf("recipeId" to recipeId)
Здесь тоже нужно использовать константу ARG_RECIPE_ID. Сейчас в созданном фрагменте ты принимаешь аргумент по ARG_RECIPE_ID, который равен recipe_id. А здесь передаешь recipeId, скорее всего у тебя падает приложение щас с IllegalArgumentException("recipe_id is required")

2024-09-26 18:02 UTC, hassantillkassan commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +                args = bundleOf("recipeId" to recipeId)
Спасибо за замечание) К счастью, приложение не падало, поскольку при передаче несоответствующего ключа `getInt("recipe_id")` возвращал значение по умолчанию 0 для отсутствующего ключа. А ноль у нас является вполне допустимым значением для айдишника рецепта (как раз таки с бургерами)

2024-09-26 18:13 UTC, ievetrovdev approved these changes
Теперь всё корректно,  молодец!

2024-09-27 16:13 UTC, merged