RA-13 recipe screen implementation
hassantillkassan/RecipesApp pull request #15
Opened 2024-10-16 17:10 UTC by hassantillkassan

2024-10-16 19:47 UTC, Churickoid requested changes

2024-10-16 19:47 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="224dp">
Не забывай выносить все значения в ресурсы

2024-10-16 19:47 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@color/white" />
Глянь внимательнее дизайн в фигме, у заднего фона есть скосы, по аналогии с текстом в шапке

2024-10-16 19:47 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@color/white" />
Такая же проблема с бэкграундом

2024-10-16 19:47 UTC, Churickoid commented on app/src/main/res/layout/item_ingredient.xml
> +        tools:text="Булочка для гамбургеров" />
Попробуй заполнить tools text длинной сплошной строкой без пробелов, текс наедет друг на друга.
Нужно добавить какой-либо ограничитель, в твоем случае достаточно будет указать
app:layout_constraintEnd_toStartOf="@id/tvIngredientQuantity"
и для второго элемента startToEnd

2024-10-16 19:47 UTC, Churickoid commented on app/src/main/res/values/dimens.xml
> +    <dimen name="divider_inset_end">12dp</dimen>
Повторять одни и те же значения ресурсов с разными айдишниками , будь то строки, цвета и dimens, плохая практика. Пусть здесь хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили. Просто дай им более обще название по типу main_space_12 и используй их в нескольких местах

2024-10-16 19:47 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +    <style name="RecyclerViewDivider">
Этот стиль нигде не используется, давай его уберем

2024-10-17 16:44 UTC, hassantillkassan commented
Здравствуйте, до этого с вами не работали. Приятно познакомиться!

2024-10-17 18:13 UTC, Churickoid approved these changes
Только недавно пришел, взаимно!
Всё верно поправил, молодец!

2024-10-18 15:45 UTC, merged