RA-15 SeekBar stylization
hassantillkassan/RecipesApp pull request #17
Opened 2024-10-21 14:01 UTC by hassantillkassan

Ещё раз по поводу значений в ресурсах. Я снова создал dimens с повторяющимися значениями. Просто, мне кажется, странно в атрибут с высотой шкалы SeekBar использовать значение margin_standard, которое также равно 16dp. Так понимание кода ухудшается. Ну либо имеет смысл переделать все названия ресурсов в dimens под более универсальные.

2024-10-21 19:19 UTC, Churickoid requested changes

2024-10-21 19:19 UTC, Churickoid commented on app/src/main/res/drawable/shape_seekbar_progress.xml
> +    <solid android:color="@color/seekBarProgressColor"/>
Цвет прогресса не соответсвует дизайну из макета

2024-10-21 19:19 UTC, Churickoid commented on app/src/main/res/values/dimens.xml
> +    <dimen name="seekbar_height">16dp</dimen>
По поводу dimens работает такая же логика как и с ресурсами строк. Если у тебя 2 строки, где написано "Категория", в таких случаях мы их объединяем и пишем новое общее название, чтобы было понятно в обоях случаях.
Нужно всм повторяющимся ресурсам в этом файле дать более общее название, чтобы не возникало непонятных контекстов. Можно дать название default_space_16 например.
Сделай для всех повторяющих ресурсов в этом файле

2024-10-22 13:44 UTC, hassantillkassan commented
По поводу цвета прогресса SeekBar. Я посмотрел по макету, по цветам в проекте и в фигме всё сходится. Или, быть может, я что-то не так понял 
![image](https://github.com/user-attachments/assets/904f2232-2f73-44f8-a926-ae433a8d3797)

2024-10-22 18:09 UTC, Churickoid approved these changes
Всё верно, молодец! С цветом это баг моего девайся был, перепроверил, действительно цвет верный, хотя на устройстве отображается другой

2024-10-23 13:27 UTC, merged