RA-23 Getting a recipe in ViewModel
hassantillkassan/RecipesApp pull request #23
Opened 2024-11-10 16:16 UTC by hassantillkassan

Здравствуйте! Извините, запушил нерабочее решение, поскольку два дня мучился, так ничего и не вышло. В общем, при открытии рецепта приложение падает. Ну, вернее не падает, а открывается дефолтный рецепт с пустым seekbar и без ингредиентов и метода приготовления. За счёт создания нового дефолтного экземпляра RecipeState через элвис  оператор
```
fun loadRecipe(recipeId: Int) {
        // TODO: load from network

        val recipe = STUB.getRecipeById(recipeId)
        val currentPortionCount = _state.value?.portionCount ?: 1
        val favorites = getFavorites()

        _state.value = _state.value?.copy(
            recipe = recipe,
            portionCount = currentPortionCount,
            isFavorite = favorites.contains(recipeId.toString()),
        ) ?: RecipeState(
            recipe = recipe,
            portionCount = currentPortionCount,
            isFavorite = favorites.contains(recipeId.toString()),
        )
    }
```
Вроде пытался всё делать аккуратно, всё равно не могу понять, в чём причина.

2024-11-10 19:36 UTC, Churickoid requested changes

2024-11-10 19:36 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +            portionCount = currentPortionCount,
Мы делаем .copy, значит все старые параметры перенесутся без изменений в новый стейт, делать манипуляции с portionCount нет смысла

2024-11-10 19:36 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +        _state.value = _state.value?.copy(isFavorite = false)
Это была тестовая строка, от неё нужно избавиться уже

2024-11-10 19:36 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeFragment.kt
>          recipe?.let { recipe ->
То что у тебя ничего не отображается - это не очень то и правильно. Причина вот здесь, переменная recipe всегда null. Вообще то что не зависит конкретно от recipe надо вынести из этой конструкции. Всё что зависит - перенести в observer и ссылаться на state.recipe и брать эти данные оттуда.

2024-11-10 19:36 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeFragment.kt
>              Log.i("!!!", "isFavorite: ${state.isFavorite}")
Этот observer уже лишний, надо убрать

2024-11-10 19:36 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeFragment.kt
> +                    viewModel.onFavoritesClicked(recipeId)
Сейчас смысла нет передавать recipeId при клике, вызывается loadRecipe где в стейте мы уже получили актуальный рецепт.  
Также каждый раз при изменении стейта будет прикрепляться новый листенер к кнопки. Всё что не зависит от данных из state - нужно выоносить из observer

2024-11-13 11:20 UTC, hassantillkassan commented
Я все эти дни сидел и переписывал один и тот же код по 10 раз, не понимая в чём проблема. Приложение падало, при открытии рецепта. И только сегодня нашёл вероятную причину. У меня централизованная навигация, завязанная на MainActivity. Так вот там при осуществлении транзакции RecipeFragment передавался не айдишник, а сам рецепт. Исправил, вроде всё заработало.
До конца не уверен, правильно ли я всё вынес из observer, но то, что приложение вновь заработало, я уже очень рад, столько вечеров мучений, а проблема была, как обычно, плёвая. Возможно, я и сам её себе создал.

2024-11-14 12:47 UTC, Churickoid requested changes

2024-11-14 12:47 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +    private val _state = MutableLiveData<RecipeState>().apply { value = RecipeState() }
в Apply нет нужды. Можно напрямую передавать в конструктор MutableLiveData

2024-11-14 12:47 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/MainActivity.kt
> +                args = bundleOf(RecipeFragment.ARG_RECIPE_ID to recipe.id)
Да, основная проблема была здесь.  Чтоб ускорить поиск ошибки рекомендую смотреть Fatal сообщения в Logcat. Там сверху-вниз написано в каких строчках кода произошли ошибки, самая близкая строчка к ошибки - вероятная причина. Там прям в Logcat можно кликнуть на номер строки и студия тебе покажет конкретную строчку в файле, очень удобно. Искать ошибки надо уметь

2024-11-14 12:47 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeFragment.kt
> +                initRecycler(recipe)
С такой реализаций появился баг. Понажимай на иконку сердечка раз 10, посмотри как меняются твой адаптер.
Нужно перенести под observer только те строки, где участвует аргумент рецепта. Все остальные функции initRecycler и тд, которые не зависят от аргумента рецепта, должны вызываться единожды вне observer.
Это улучшить производительность и пофиксит баг

2024-11-14 17:45 UTC, Churickoid approved these changes
По заданию всё верно, молодец! Апрув

2024-11-14 17:45 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeFragment.kt
> +        val recipe = viewModel.state.value?.recipe ?: return
Единственный источник данных - стейт внутри observer. Всё остальное обращение к стейту вне observer может породить рассинхрон между актуальным стейтом и пришедшим. Это нарушает принцип MVVM.
Запомни этот коммент, в RA-25 мы будем работать с рефакторингом адаптеров, там поправь

2024-11-15 14:36 UTC, merged