RA-28 Jetpack Navigation implementation
hassantillkassan/RecipesApp pull request #28
Opened 2024-11-22 16:51 UTC by hassantillkassan

2024-11-22 22:41 UTC, Churickoid requested changes
Одна из проблем прошлой реализации и она сейчас присутсвует, но на jetpack navigetion мы её можем поправить:
Попробуй 10 раз подряд нажать на кнопку Категорий, все они попадут в backstack, чтобы их все закрыть придется нажать 10 раз на кнопку назад. Для action можно прописать параметр app:launchSingleTop="true", но для фрагментов из MainActivity это не сработает, поскольку они без action. Придется сделать по другому, создать navOptions и прописать эти настройки:
```
findNavController(R.id.mainContainer).navigate(
                R.id.favoritesListFragment,
                null,
                navOptions {
                    launchSingleTop = true
                })
```

2024-11-22 22:41 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/MainActivity.kt
> +            navController.navigate(R.id.categoriesListFragment)
Фрагменты между собой должны управляться через Actions. В nav_graph мы нужно соединить стрелками  фрагменты, так мы дадим знать разработчикам как схематично устроена навигация у нас в проекте. Каждая стрелка генерирует action - их можно настраивать. И .navigate должен выполняться через эти экшены

2024-11-24 12:24 UTC, hassantillkassan commented
Долго думал, как предусмотреть навигацию на экраны "Избранное" и "Категории" со всех экранов, а не только с CategoriesListFragment и FavoritesFragment соответственно. В итоге решил попробовать через action_global. Как вам?

2024-11-24 21:35 UTC, Churickoid approved these changes
Хороший подход с использованием глобальных экшенов, возможно даже лучше предложенной реализации. Но так проблема и воспроизводится, которую я описывал "Попробуй 10 раз подряд нажать на кнопку Категорий, все они попадут в backstack", не добавил экшенам нужный атрибут

Поправь эти проблемы в следующем ПР

2024-11-24 21:35 UTC, Churickoid commented on app/src/main/res/navigation/nav_graph.xml
> +            app:destination="@id/categoriesListFragment" />
Сейчас происходит хаос на графе. При взгляде на граф, разработчик должен увидеть из какого фрагмента можно попасть на другой фрагмент. Мы должны отразить все перемещения на этом графике. То есть из экрана избранного можно попасть только на экран рецепа. Экран рецепта никуда не идет - это тупик
![image](https://github.com/user-attachments/assets/6300a7ae-8b6d-4d44-b377-dd510833d564)

2024-11-24 21:35 UTC, Churickoid commented on app/src/main/res/navigation/nav_graph.xml
> +        app:destination="@+id/recipeFragment"/>
Этот экшен лишний

2024-11-25 13:27 UTC, merged