RA-35 Retrofit implementation
hassantillkassan/RecipesApp pull request #34
Opened 2024-12-04 15:31 UTC by hassantillkassan

Что-то я не так сделал. Приложение ужасно себя ведёт. Начиная от загрузки рецептов, которая происходит с задержкой, заканчивая багом с добавлением в избранное и открытием рецептов других категорий. Проблема кроется в потоках во viewmodel?

2024-12-04 20:45 UTC, Churickoid requested changes
То что работает загрузка с задержкой - этого мы и добивались. Теперь приложение ходит в сеть на сервер, это операция не моментальная. По хорошему нужно добавить какие-то вьюхи загрузки, но курс не расчитан на это. Но после исправлений комментов, должно стать по быстрее. Эти комменты общие для всех экранов, поправь их везде.
Еще уже нужно убрать из main activity тестовые запросы, они уже нужны.
Также покликай по другим рецептам из новой категории, на некоторых крешится приложение. Нужно корректно обработать null в адаптере

2024-12-04 20:45 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/favorites/FavoritesViewModel.kt
> +    private val executor = Executors.newSingleThreadExecutor()
Создавать треды - достаточно тяжелая операция. Также при нескольких операций в пуле не хватит потоков для обработки. Предлагаю создать object ThreadPoolProvider, там создать
private val threadPool: ExecutorService = Executors.newFixedThreadPool(10) и обращаться к ним во всех viewModel

2024-12-04 20:45 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/favorites/FavoritesViewModel.kt
> +                    ).show()
Создание toast это часть UI, это должно находится на уровне фрагмента, viewModel работает с данными. Мы должны отправлять в observer например favoriteRecipes = null, а во фрагменте обрабатывать этот стейт с выводом toast

2024-12-04 20:45 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/favorites/FavoritesViewModel.kt
> +                }
Handler post использовать не надо, liveData потокобезопасные и так. Только нужно использовать не обычное присвоение, а postValue в таких случаях

2024-12-04 20:45 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/favorites/FavoritesViewModel.kt
> +            val favoriteRecipes = recipesRepository.getRecipesByIds(favoritesIds)
При вызове этого метода, твой поток крэшится. Нужно добавить try catch, чтоб хоть что-то логировалось в логкэт. По дефолту логкэт логирует только креши мэин потока. 
А проблема вызвана с тем, что в документации API мы должны передавать строку айдишников через запятую, а не список. Нужно переписать. 
Сейчас вообще экран избранного не работает, нужно его починить, возможно, это не единственная проблема

2024-12-05 11:43 UTC, hassantillkassan commented
По поводу отображения Toast было два варианта:

2024-12-05 16:02 UTC, Churickoid approved these changes
В целом всё верно исправил, молодец! Поправь только небольшие комменты в следующем ПР.
По поводу размера задника у текста шапки, я это править не требую, но если получится - похвалю) В целом достаточно ограничить в сonstraint по End родителя ширину, тогда проблем не будет. Но он сползет из-за этого на центр экрана, на решить этот момент

2024-12-05 16:02 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +                        errorMessage = "Ошибка получения данных",
В целом текущих подход с ошибками неплохой. Но есть два косяка, которые нужно поправить:
1) Если зайти на экран без интернета, получить тост, включить интернет, повернуть экран. Тост будет слаться каждый раз, даже если интернет уже появился и данные загрузились. Нужно обнулять переменную errorMessage при корректной загрузке.
2) Текущая реализация не поддерживает локализацию, всегда будет сообщение на русском. Можно создать enum класс с типом ошибок и передавать их. В зависимости от типа ошибки, дергать определенную строку из ресурсов

2024-12-05 16:02 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/categories/CategoriesListViewModel.kt
> +        executor.execute {
В целом можно напрямую обращаться к hreadPoolProvider.threadPool.execute. Эта переменная сейчас выглядит лишней

2024-12-06 11:48 UTC, merged