RA-36 Uploading and processing images with Glide
hassantillkassan/RecipesApp pull request #35
Opened 2024-12-11 16:34 UTC by hassantillkassan

Ошибки для Toast переехали в отдельный enum класс ErrorType. Также основные константы теперь тоже находятся в отдельном файле

2024-12-12 09:18 UTC, Churickoid requested changes

2024-12-12 09:18 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/favorites/FavoritesFragment.kt
> +            state.error?.let { error ->
Лучше не показывать надпись "Вы не добавили ни одного рецепта" при сетевой ошибки, это только запутает пользователя. Только тост

2024-12-12 09:18 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/list/RecipesListFragment.kt
> +                    .into(recipesBinding.ivCategoryCoverImage)
Вообще можно все эти вызовы глайда вынести в отдельную спомогательную функцию, поскольку placeholder и error будет везде одинаковым.
Лучше всего это сделать через функцию расширения context.loadImage в отдельном классе, например ImageLoaderUtils

2024-12-12 09:20 UTC, Churickoid commented
По поводу груши, ничего фиксить не надо. Просто посмотреть за поведением библиотеки. Библиотека Glide кэширует все фотки, поэтому при повторных обращениях, она уже работает без задержки

2024-12-12 16:56 UTC, hassantillkassan commented
Я решил полностью переделать логику отображения элементов интерфейса в FavoritesFragment, чтобы ещё убрать заглушку "Вы не добавили ни одного рецепта в Избранное" во время загрузки избранных рецептов.

Потом ещё появился баг: при наличии сетевого подключения и отсутствия рецептов в Избранном, на экране появлялся Тост с сетевой ошибкой, вместо заглушки. В итоге пофиксил его проверкой `if (favoritesIds.isEmpty())` с выходом из лямбды return@execute

2024-12-13 07:11 UTC, Churickoid reviewed
Молодец, всё верно

2024-12-13 07:13 UTC, Churickoid approved these changes

2024-12-13 14:04 UTC, merged