RA-38 Jetpack Room implementation
hassantillkassan/RecipesApp pull request #37
Opened 2024-12-15 13:51 UTC by hassantillkassan

Закэшированные файлы изображений Glide
![кэш изображений Glide](https://github.com/user-attachments/assets/f54fee94-83df-411b-9b08-1e94ecb1cdac)

Файл shared prefs
![shared prefs](https://github.com/user-attachments/assets/b75608cf-f815-43d6-ad6c-3aeb590c872f)

2024-12-15 14:00 UTC, hassantillkassan commented
Прошлые замечания тоже поправил в RecipesRepository

2024-12-15 17:58 UTC, Churickoid requested changes

2024-12-15 17:58 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +        sharedPrefs.edit().putStringSet(Constants.FAVORITES_KEY, favorites).apply()
По сути выносить в глобальные константы имеет смысл, только когда она используется в нескольких разных классах. Сейчас достаточно приватные константы в companion object указать

2024-12-15 17:58 UTC, Churickoid commented on gradle/libs.versions.toml
> +androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
необходимо еще добавить androidx.room:room-compiler, в документации про это сказано

2024-12-15 17:58 UTC, Churickoid commented on app/build.gradle.kts
> +    id("com.google.devtools.ksp") version "1.9.0-1.0.13"
нужно вынести в toml файл

2024-12-16 08:58 UTC, Churickoid approved these changes
Молодец, всё верно! Не увидел, что у тебя до этого эти константы участвовали в двух viewModel, прошлая реализация была верной. Можешь в следующем ПР откатить изменения этих файлов через revert конкретного файла в github

2024-12-16 13:58 UTC, merged