RA-41 Storing Favorites in Room
hassantillkassan/RecipesApp pull request #40
Opened 2024-12-22 16:42 UTC by hassantillkassan

2024-12-23 14:48 UTC, Churickoid requested changes

2024-12-23 14:48 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +                val recipeImageUrl = Constants.BASE_URL + Constants.IMAGES_PATH + recipe?.imageUrl
Давай здесь использовать твой новый метод updatedImageUrl

2024-12-23 14:48 UTC, aGroupoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/favorites/FavoritesViewModel.kt
> +                        isLoading = false,
Можем ли полностью отказаться от isLoading и проверять error != null или нет?

2024-12-23 14:48 UTC, Churickoid commented on app/src/main/java/com/example/recipesapp/ui/recipes/detail/RecipeViewModel.kt
> +                val isFavorite = favorites.contains(recipeId.toString())
Мы должны полностью избавиться от SharedPreferences, локальная бд умеет делать всё что и преференсис, только делает это лучше. Всё должно работать через запрос к БД

2024-12-23 17:05 UTC, hassantillkassan commented
По поводу isLoading. Он может быть полезен, чтобы, как минимум разделить три состояния на экране Favorites:
1) Загрузка isLoading = true, error = nul
2) Успешная загрузка isLoading = false, error = null
3) Ошибка isLoading = false, error != null

Если уберем его, то уже не сможем отследить процесс загрузки избранных рецептов. И хоть в UI мы не используем никаких индикаций загрузки, в будущем их можно допилить. Ну плюс также isLoading можно комбинировать с состоянием ошибок/использовать для оптимизации производительности (избегать ненужных запросов и тд). Я так понимаю назначение isLoading

2024-12-24 15:28 UTC, Churickoid approved these changes
Молодец, по заданию всё верно! В целом мы можем отследить загрузку по recipe != null

2024-12-24 16:20 UTC, merged