RA 05 button navigation
hassantillkassan/RecipesApp pull request #7
Opened 2024-08-31 14:50 UTC by hassantillkassan

2024-08-31 20:14 UTC, ievetrovdev requested changes

2024-08-31 20:14 UTC, ievetrovdev commented on gradle/libs.versions.toml
> +androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
зачем её подключал? Лишняя библиотека, без неё все корректно собирается.

2024-08-31 20:14 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +    private fun navigateToFragment(fragment: Fragment) {
Молодец, что вынес в отдельный метод, но давай сделаем еще лучше через inline функцию:
binding.bCategories.setOnClickListener {
navigateToFragment<CategoriesListFragment>()
}

binding.bFavorites.setOnClickListener {
navigateToFragment<FavoritesFragment>()
}

private inline fun <reified T : Fragment> navigateToFragment() {
supportFragmentManager.commit {
setReorderingAllowed(true)
replace<T>(binding.mainContainer.id)
}
}

2024-09-01 16:08 UTC, hassantillkassan commented
По поводу метода a`ddToBackStack()`. Стоит ли его оставлять? Потому что на данном этапе разработки приложения добавление текущей транзакции фрагментов в задний стек системы управления фрагментами работает, мягко говоря, коряво. Что я имею в виду?

2024-09-02 11:27 UTC, ievetrovdev commented
> По поводу метода `addToBackStack()`. Стоит ли его оставлять? Потому что на данном этапе разработки приложения добавление текущей транзакции фрагментов в задний стек системы управления фрагментами работает, мягко говоря, коряво. Что я имею в виду? На эмуляторе, если один раз нажать кнопку "Избранное", то перейти к предыдущему фрагменту с категориями можно при помощи одного свайпа от левого края (ну или при помощи кнопки "назад" - зависит уже от устройства). Но, если нажать на кнопку "Избранное", к примеру, три раза, то вернуться на фрагмент с категориями получится лишь при помощи трёх таких свайпов. Ну, грубо говоря, здесь не работает "защита от дурака". Пользователь может хоть 20 раз нажать на кнопку "Избранное" или "Категории" и тогда весь смысл метода `addToBackStack()` пропадает

Да, хорошое замечание. Давай добавим очистку бэк стека при нажатии на нижние кнопки навигации. 
Так путь из вложенный фрагментов категории -> список рецептов -> рецепт будет корректно происходить и ситуации с 10 фрагментами не будет. 
Вообще это сейчас для обучения работы с фрагменты мы делаем, далее по курсу мы перепишем навигацию на Jetpack Navigation, там таких проблем не будет

2024-09-02 11:27 UTC, ievetrovdev requested changes

2024-09-02 11:27 UTC, ievetrovdev commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +    private inline fun navigateToFragment(fragmentProvider: () -> Fragment) {
Немного не того я хотел. Гитхаб зажевал слова внутри `<>`. Он считает их гиперссылкой. 
Щас продублирую корректно тот код:
```
binding.bCategories.setOnClickListener {
    navigateToFragment<CategoriesListFragment>()
}

binding.bFavorites.setOnClickListener {
    navigateToFragment<FavoritesFragment>()
}

private inline fun <reified T : Fragment> navigateToFragment() {
    supportFragmentManager.commit {
        setReorderingAllowed(true)
        replace<T>(binding.mainContainer.id)
    }
}
```

2024-09-02 15:43 UTC, hassantillkassan commented on app/src/main/java/com/example/recipesapp/MainActivity.kt
> +    private inline fun navigateToFragment(fragmentProvider: () -> Fragment) {
Функция слегка ввела в ступор, тк ранее не работал с дженериками, но вроде разобрался.

2024-09-03 17:37 UTC, ievetrovdev commented
Сейчас проблема такая, что ты очищаешь backStack, а твой первый фрагмент не лежит в нём, из-за этого всё равно остаётся рутовый фрагмент и к нему кладется новый. Хорошого решения не придумать,  если хочешь оставь пока такое, только замени просто на popBackStack, ломается анимация. Базовая работа с фрагментами не особо удобная, для этого и придумали Jetpack Navigation, но с ней мы будем работать дальше.

2024-09-03 17:37 UTC, ievetrovdev commented
также у тебя поехали кнопки навигации, одна выше другой

2024-09-03 19:58 UTC, ievetrovdev approved these changes
Апрувлю, маленькую проблему поправь уже в следующей задаче
Попробуй уменьшить размер макета в студии, одна кнопка выше другой. У кнопки по стандарту свой padding есть, пропиши в стиле android:padding="0dp" и проблема уйдет
<img width="293" alt="Снимок экрана 2024-09-03 в 22 51 43" src="https://github.com/user-attachments/assets/477924a6-de03-4992-b729-d23960d3adf8">

2024-09-03 20:12 UTC, merged