RA-07 category list screen layout
hassantillkassan/RecipesApp pull request #9
Opened 2024-09-05 18:57 UTC by hassantillkassan

2024-09-05 19:00 UTC, hassantillkassan commented
С неймингом коммита немного промахнулся, не обращайте на него внимание. `ripple_background.xml` создал, чтобы в дальнейшем поэкспериментировать c созданием кастомного блеска при нажатии на view в списке

2024-09-05 19:14 UTC, ievetrovdev requested changes

2024-09-05 19:14 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:layout_marginVertical="@dimen/margin_standard"/>
Добавь еще атрибут tools:listitem="@layout/item_category". Так ты увидишь на превьюхе в студии сверстанные карточки категории и как они будут выглядеть в приложении.

Карточку надо сверстать. Представь, что элемент списка – это вот весь данный лейаут. Сделай для него верстку, заполни тестовыми данными в качестве картинки, названия и описания через атрибуты tools.

2024-09-05 19:14 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:padding">10dp</item>
значение в ресурсы

2024-09-05 19:14 UTC, ievetrovdev commented on app/src/main/res/values-ru/strings.xml
> +    <string name="recipe_categories_title">Категории</string>
recipe_categories_title дублирает текст button_category, так делать не надо. Назови как-то обобщенно,  например text_category, и используй ресурс в двух местах

2024-09-07 17:17 UTC, ievetrovdev approved these changes
Молодец, всё соотвествует дизайну. В item_category у imageView также можно добавить tools:ignore="ContentDescription",  поскольку этот параметр будет динамическим для элементов адаптера

2024-09-08 15:49 UTC, merged